// <auto-generated />
using System;
using Gvn.IceCream.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gvn.IceCream.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240907194919_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.IceCream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IceCreams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_0.jpg",
                            Name = "Vanilla Delight",
                            Price = 1.5
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_1.jpg",
                            Name = "Chocolate Heaven",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_2.jpg",
                            Name = "Strawberry Dream",
                            Price = 3.5
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_3.jpg",
                            Name = "Mint Chocolate Chip",
                            Price = 4.5
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_4.jpg",
                            Name = "Cookies and Cream",
                            Price = 5.5
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_5.jpg",
                            Name = "Butter Pecan",
                            Price = 6.5
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_6.jpg",
                            Name = "Rocky Road",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_7.jpg",
                            Name = "Pistachio",
                            Price = 8.5
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_8.jpg",
                            Name = "Neapolitan",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_9.jpg",
                            Name = "Birthday Cake",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_10.jpg",
                            Name = "Birthday Cake",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_11.jpg",
                            Name = "Birthday Cake",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_12.jpg",
                            Name = "Birthday Cake",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_13.jpg",
                            Name = "Birthday Cake",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_14.jpg",
                            Name = "Birthday Cake",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_15.jpg",
                            Name = "Bluee bake Cake",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 17,
                            Image = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_16.jpg",
                            Name = "Bluee bake Cake",
                            Price = 10.5
                        });
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.IceCreamOptions", b =>
                {
                    b.Property<int>("IcecreamId")
                        .HasColumnType("int");

                    b.Property<string>("Flavor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Topping")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IcecreamId", "Flavor", "Topping");

                    b.ToTable("IceCreamOptions");

                    b.HasData(
                        new
                        {
                            IcecreamId = 1,
                            Flavor = "Vanilla",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 1,
                            Flavor = "Default",
                            Topping = "Chocolate Sauce"
                        },
                        new
                        {
                            IcecreamId = 2,
                            Flavor = "Chocolate",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 2,
                            Flavor = "Strawbery",
                            Topping = "Whipped"
                        },
                        new
                        {
                            IcecreamId = 2,
                            Flavor = "Chocolate",
                            Topping = "Muz"
                        },
                        new
                        {
                            IcecreamId = 3,
                            Flavor = "Strawberry",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 4,
                            Flavor = "Mint",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 5,
                            Flavor = "Cookies",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 6,
                            Flavor = "Butter",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 7,
                            Flavor = "Rocky",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 8,
                            Flavor = "Pistachio",
                            Topping = "Default"
                        },
                        new
                        {
                            IcecreamId = 9,
                            Flavor = "Neapolitan",
                            Topping = "Default"
                        });
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IcecreamId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderId1")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Topping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId1");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.IceCreamOptions", b =>
                {
                    b.HasOne("Gvn.IceCream.API.Data.Entities.IceCream", "Icecream")
                        .WithMany("Options")
                        .HasForeignKey("IcecreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icecream");
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("Gvn.IceCream.API.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.IceCream", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Gvn.IceCream.API.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
